### ISSUE TITLE
log 的api接口

### ISSUE THREAD

**Issue by vitan** [Dataman-Cloud/omega-api-docs#5]
- 添加之前阅读readme
- apidoc.shurenyun.com
- 具体问题跟 @wuti1609  确认。

**Comment by wuti1609** [comment]
这个跟国强讨论一下吧，感觉不是只暴露 es query 那么简单。

**Comment by yqguodataman** [comment]
我感觉最好还是不要直接在页面上去访问es。

**Comment by leonlee** [comment]
需要包装es的api，统一查询入口，条件为app等业务约束，否则客户无法使用 goto https://trello.com/c/3I2XEF7N
